<?php
/**
 * Created by IntelliJ IDEA.
 * User: Svetoslav Kostadinov
 * Date: 1/31/13
 * Time: 10:51 PM
 * To change this template use File | Settings | File Templates.
 */

?>
<!-- Footer -->
<div id="footer-wrapper">
    <footer id="footer" class="5grid-layout">
        <div class="row">
            <div class="8u">

                <!-- Links -->
                <section>
                    <h2>Links to Important Stuff</h2>
                    <div class="5grid">
                        <div class="row">
                            <div class="3u">
                                <ul class="link-list last-child">
                                    <li><a href="#">Neque amet dapibus</a></li>
                                    <li><a href="#">Sed mattis quis rutrum</a></li>
                                    <li><a href="#">Accumsan suspendisse</a></li>
                                    <li><a href="#">Eu varius vitae magna</a></li>
                                </ul>
                            </div>
                            <div class="3u">
                                <ul class="link-list last-child">
                                    <li><a href="#">Neque amet dapibus</a></li>
                                    <li><a href="#">Sed mattis quis rutrum</a></li>
                                    <li><a href="#">Accumsan suspendisse</a></li>
                                    <li><a href="#">Eu varius vitae magna</a></li>
                                </ul>
                            </div>
                            <div class="3u">
                                <ul class="link-list last-child">
                                    <li><a href="#">Neque amet dapibus</a></li>
                                    <li><a href="#">Sed mattis quis rutrum</a></li>
                                    <li><a href="#">Accumsan suspendisse</a></li>
                                    <li><a href="#">Eu varius vitae magna</a></li>
                                </ul>
                            </div>
                            <div class="3u">
                                <ul class="link-list last-child">
                                    <li><a href="#">Neque amet dapibus</a></li>
                                    <li><a href="#">Sed mattis quis rutrum</a></li>
                                    <li><a href="#">Accumsan suspendisse</a></li>
                                    <li><a href="#">Eu varius vitae magna</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </section>

            </div>
            <div class="4u">

                <!-- Blurb -->
                <section>
                    <h2>An Informative Text Blurb</h2>
                    <p>
                        Duis neque nisi, dapibus sed mattis quis, rutrum accumsan sed. Suspendisse eu
                        varius nibh. Suspendisse vitae magna eget odio amet mollis. Duis neque nisi,
                        dapibus sed mattis quis, sed rutrum accumsan sed. Suspendisse eu varius nibh
                        lorem ipsum amet dolor sit amet lorem ipsum consequat gravida justo mollis.
                    </p>
                </section>

            </div>
        </div>
    </footer>
</div>
