<?php
/**
 * Created by IntelliJ IDEA.
 * User: Svetoslav Kostadinov
 * Date: 1/31/13
 * Time: 10:53 PM
 * To change this template use File | Settings | File Templates.
 */ ?>

<!-- Header -->
<div id="header-wrapper">
    <header id="header" class="5grid-layout">
        <div class="row">
            <div class="12u">

                <!-- Logo -->
                <h1><a href="#" class="mobileUI-site-name">Halcyonic</a></h1>

                <!-- Nav -->
                <nav class="mobileUI-site-nav">
                    <a href="index.html">Homepage</a>
                    <a href="threecolumn.html">Three Column</a>
                    <a href="twocolumn1.html">Two Column #1</a>
                    <a href="twocolumn2.html">Two Column #2</a>
                    <a href="onecolumn.html">One Column</a>
                </nav>

            </div>
        </div>
    </header>
    <div id="banner">
        <div class="5grid-layout">
            <div class="row">
                <div class="6u">

                    <!-- Banner Copy -->
                    <p>We do something really useful, important, and unique. Learn all about it here ...</p>
                    <a href="#" class="button-big">Go on, click me!</a>

                </div>
                <div class="6u">

                    <!-- Banner Image -->
                    <a href="#" class="bordered-feature-image"><img src="assets/images/banner.jpg" alt="" /></a>

                </div>
            </div>
        </div>
    </div>
</div>