<!DOCTYPE HTML>
<!--
	Halcyonic 2.5 by HTML5 Up!
	html5up.net | @n33co
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
<head>
    <title>Halcyonic: A Responsive HTML5 Site Template by HTML5 Up! (Homepage)</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />

    <?php
        echo $this->headTitle();
        echo $this->headScript();
        echo $this->headStyle();
    ?>

    <noscript>
        <link rel="stylesheet" href="assets/css/5grid/core.css" />
        <link rel="stylesheet" href="assets/css/5grid/core-desktop.css" />
        <link rel="stylesheet" href="assets/css/5grid/core-1200px.css" />
        <link rel="stylesheet" href="css/5grid/core-noscript.css" />
        <link rel="stylesheet" href="css/style.css" />
        <link rel="stylesheet" href="css/style-desktop.css" />
    </noscript>
    <script src="assets/css/5grid/jquery.js"></script>
    <script src="assets/css/5grid/init.js?use=mobile,desktop,1000px&amp;mobileUI=1&amp;mobileUI.theme=none&amp;mobileUI.titleBarHeight=55&amp;mobileUI.openerWidth=75&amp;mobileUI.openerText=&lt;"></script>
    <!--[if lte IE 9]><link rel="stylesheet" href="assets/css/style-ie9.css" /><![endif]-->
</head>
<body>

    <?php echo $this->layout()->content; ?>

</body>
</html>